### ISSUE TITLE
Rotation to target

### ISSUE THREAD

**Issue by Juris3D** [mklabs/ue4-targetsystemplugin#4]
Hello. Thank You for plugin. Trying on 4.21. Targeting works, scrolling between targets too, but i can not turn off "rotation to target". I unchecked in component, even made key input flip/flop that should change that bool inside component, but in my case, "look at target" mode is On all the time. What could be my mistake here? Thank You.

**Comment by mklabs** [comment]
Hello,

Are you referring to the option "Should Control Rotation When Locked On" ?

![image](https://user-images.githubusercontent.com/113832/59677942-6e835480-91cb-11e9-8f6f-c77900ae3444.png)

I'm not sure why you get this behaviour. I didn't encountered this issue on several projects. Turning it off in the component's default or in blueprint should work.

Can you describe a bit more your setup, maybe by providing screenshots ? I don't know if you can but if the project is not confidential or too voluminous, maybe you could send me your project so that I can try to reproduce and see what's going on ?

**Comment by Juris3D** [comment]
Hello. Thank You for trying to help. Yes, I am referring to that option, "Should control rotation". Here I uploaded absolutely clean 3rd person template project 4.21 (just 20MB), with nothing else added, just Target plugin enabled, and Target component added to character BP. In that BP, two actions added: Targeting "T" and LookAt "B", with printstring indications. Player is circling locked target (other characer in map) no matter of value of that "rotation" setting. Sorry if I am missing something too obvious. Thank You.
Project: https://drive.google.com/open?id=1XNjbvnK5kslkix8P78QINp8KBWHa-u40

**Comment by mklabs** [comment]
Hi.

Thanks for providing more info and and project setup. I see, this is actually the expected behaviour. This option just control whether or not your character should "face" the target.

When the option is turned off, the character can move around freely, eg. when going left the character forward vector is going left, when going right its forward vector is going right. But the character camera is still locked to the target.

When the option is turned on, the character forward vector will always be facing the target. It is advised to use this option if you are able to setup strafe animations when locked on.
