### ISSUE TITLE
[Question] Return object aimed at and moving camera

### ISSUE THREAD

**Issue by EspectroRebelde** [mklabs/ue4-targetsystemplugin#5]
Hi! First of all, thanks for the amazing plugin and how well it's done! 

I was trying it on **4.22** and was trying to do two things that I'm not sure if the plugin allows, is it possible to get the target you're aiming to? Like have a return value that is the target of the plugin or similar, and, is it possible to change the angle of the camera so it's not fixed to the target point? To have a more wide area of view or in case some characters are too big or weird and they can't be properly played with when the camera is that way. 

Again, thanks for the amazing work and in advance!

**Comment by mklabs** [comment]
Hi, thanks for the kind words ;)

>  Is it possible to get the target you're aiming to?

I usually do it with the two main events exposed by the component "OnTargetLockedOn" and "OnTargetLockedOff". They both pass in the actor that is targeted or was in target, so you can take this variable and have it stored in your blueprints.

I guess I could also expose a function that would return the targeted actor if any, that would be fairly simple to do on the cpp side.

> is it possible to change the angle of the camera so it's not fixed to the target point?

I just had the use case for it on a game I'm currently developing and made a slight modification to this plugin to allow that. My need was that for some character that were smaller than my main character, the closer I was to the target actor, the lower the camera pitch became (end of the camera spring arm was way too low) resulting in the player not having a clear line of sight to his target (hidden behind the main character basically).

I fixed it by changing the [SetControlRotation](https://github.com/mklabs/ue4-targetsystemplugin/blob/master/TargetSystem/Source/TargetSystem/Private/TargetSystemComponent.cpp#L421) method to broadcast an event if it is bound and implemented in blueprint, falling back to the default cpp implementation if it is not.

It allows further control on how you set the controller rotation (and the camera), by doing it in blueprint instead of the plugin default behavior. This is then your responsibility to calculate the control rotation based on the actor and target location (like the plugin does), optionally applying an offset to the rotator (like I did for my game based on the distance to target), and applying this rotation with "SetControlRotation.

I was planning on pushing this out, but if you're interested, I can maybe push the changes I did tomorrow, with a wiki page explaining how I did that. If you're willing to use the plugin source from github, you could probably do the same and apply your custom logic to the rotation.

**Comment by EspectroRebelde** [comment]
With what you told me I managed to make both things work rather nicely so thanks a lot for the answer and for how fast it was! 

I personally think that the actor targetted is perfect how it is right now and the camera part is something a lot of people will really care about and really appreciate but there is no need to rush it since it seems  that it hasn't been a big issue for what people seem to have been worried about so it would be a nice addition but just do it when you have time and think it's time to push the changes you make out! 

And once again, thanks a lot for your work and all, it truly means a lot especially to people like me that are more starting with ue4 and similar and use projects like these to learn better instead of tutorials so thanks for making the community a better place for us all!

**Comment by mklabs** [comment]
Glad to hear ;)
